FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Setenv variables during build if necessary
ENV PUBLIC_API_BASE_URL=http://localhost:8000

RUN npm run build

# Runtime Stage
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT=3000
CMD ["node", "build/index.js"]