[package]
name = "shared"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Database
sea-orm = { workspace = true }
entity = { path = "../entity" }

# Async
tokio = { workspace = true }
async-trait = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Utilities
dotenvy = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

# Serialization
serde = { workspace = true }
